sudo: required

services:
  - docker

env: SH="docker exec -t ubuntu-test bash -c"

before_install:
  - docker build -t shape_completion .
  - docker run -d --name "ubuntu-test" -v $(pwd):/travis -w /travis shape_completion tail -f /dev/null
  - docker ps

install:
  - $SH "pyclean"
  
script:
  - $SH "pytest"

after_script:
  - docker images
